test _MSC_VER instead of _WIN32 for stuff specific to Visual Studio (#49)
otherwise, cross-compiling for MingW32 with i686-w64-mingw32-g++-posix
-Werror fails with the following diagnosis

robin_hood.h:116: error: ignoring #pragma intrinsic  [-Werror=unknown-pragmas]
 #    pragma intrinsic(ROBIN_HOOD(BITSCANFORWARD))

But really __builtin_ctzl() is available, since it's GCC.